//! Hand-written entrypoint for `buf generate` output.
//!
//! This file is committed; the files it `include!()`s are NOT (see
//! .gitignore) — they are regenerated by `buf generate` from `proto/`
//! after clone or after editing a `.proto` file.
//!
//! Verified against real output for the `open6gair.v1` package:
//! `buf generate` writes two files under
//! `src/open6gair/v1/`:
//!   - `open6gair.v1.rs`       (protoc-gen-prost: message/enum types)
//!   - `open6gair.v1.tonic.rs` (protoc-gen-tonic: gRPC client/server stubs)
//!
//! `open6gair.v1.rs` itself contains `include!("open6gair.v1.tonic.rs");`
//! at the end — protoc-gen-prost pulls in the tonic file automatically
//! when a service is defined for the same package. Only the prost file
//! needs to be included here; including the tonic file a second time
//! causes duplicate module definitions (E0428).

pub mod open6gair {
    pub mod v1 {
        include!("open6gair/v1/open6gair.v1.rs");
    }
}
